export interface UnitPlan {
	user: string,
	id: string,
	schoolName: string,
	sectionName: string,
	sectionId: string,
	level: string,
	duration: number,
	learningSituation: string,
	title: string,
	specificCompetences: {
    comunicativa: string[],
    pensamientoLogicoCreativoYCritico: string[],
    resolucionDeProblemas: string[],
    eticaYCiudadana: string[],
    cientificaYTecnologica: string[],
    ambientalYDeLaSalud: string[],
    desarrolloPersonalYEspiritual: string[],
  },
	mainThemeCategory: string,
	mainThemes: string[],
	subjectNames: string[],
	strategies: string[],
	evaluationCriteria: {
    comunicativa: string[],
    pensamientoLogicoCreativoYCritico: string[],
    resolucionDeProblemas: string[],
    eticaYCiudadana: string[],
    cientificaYTecnologica: string[],
    ambientalYDeLaSalud: string[],
    desarrolloPersonalYEspiritual: string[],
  },
	contents: {
    subject: string,
    concepts: string[],
    procedures: string[],
    attitudes: string[],
    achievement_indicators: string[]
  }[],
  resources: string[],
  instruments: string[],
  teacher_activities: string[],
  student_activities: string[],
  evaluation_activities: string[],
}
