export interface UnitPlan {
	uid: string,
	id: string,
	schoolName: string,
	sectionName: string,
	sectionId: string,
	level: string,
	duration: number,
	learningSituation: string,
	title: string,
	specificCompetences: { Comunicativa: string[], PensamientoLogico: string[], EticaYCiudadana: string[] },
	mainThemeCategory: string,
	mainThemes: string[],
	subjectNames: string[],
	strategies: string[],
	evaluationCriteria: { Comunicativa: string[], PensamientoLogico: string[], EticaYCiudadana: string[] },
	contents: { subject: string, concepts: string[], procedures: string[], attitudes: string[], achievement_indicators: string[] }[],
    resources: string[],
    instruments: string[],
    teacher_activities: string[],
    student_activities: string[],
    evaluation_activities: string[],
}
