export enum SchoolSubject {
    LENGUA_ESPANOLA = 'LENGUA_ESPANOLA',
    MATEMATICA = 'MATEMATICA',
    CIENCIAS_SOCIALES = 'CIENCIAS_SOCIALES',
    CIENCIAS_NATURALES = 'CIENCIAS_NATURALES',
    INGLES = 'INGLES',
    FRANCES = 'FRANCES',
    EDUCACION_ARTISTICA = 'EDUCACION_ARTISTICA',
    EDUCACION_FISICA = 'EDUCACION_FISICA',
    FORMACION_HUMANA = 'FORMACION_HUMANA',
    TALLERES_OPTATIVOS = 'TALLERES_OPTATIVOS',
}
