export enum SCHOOL_SUBJECT {
	LENGUA_ESPANOLA,
	MATEMATICA,
	CIENCIAS_SOCIALES,
	CIENCIAS_NATURALES,
	INGLES,
	FRANCES,
	EDUCACION_ARTISTICA,
	EDUCACION_FISICA,
	FORMACION_HUMANA,
	TALLERES_OPTATIVOS,
}
