export type SchoolSubject =
	| 'LENGUA_ESPANOLA'
	| 'MATEMATICA'
	| 'CIENCIAS_SOCIALES'
	| 'CIENCIAS_NATURALES'
	| 'INGLES'
	| 'FRANCES'
	| 'FORMACION_HUMANA'
	| 'EDUCACION_FISICA'
	| 'EDUCACION_ARTISTICA'
	| 'TALLERES_OPTATIVOS';
