import { AppEntry } from '../core';

export const activitiesTools: AppEntry[] = [
	{
		link: '/activities/english-dialog-generator',
		name: 'Conversaciones en Inglés',
		description: 'Diálogos en inglés por nivel.',
		icon: '/assets/dialog.svg',
		tier: 1,
	},
	{
		name: 'Generador de Lecturas Guiadas',
		description: 'Genera actividades de lectura de cualquier nivel.',
		link: '/activities/guided-reading-generator',
		icon: '/assets/icons/education/PNG/creativity-svgrepo-com.png',
		tier: 1,
	},
	{
		name: 'Actividades para Efemérides',
		description: 'Actividades únicas para cada commemoración',
		link: '/activities/holiday-activity-generator',
		icon: '/assets/undraw_festivities_q090.svg',
		tier: 1,
	},
	{
		name: 'Ordena las Palabras',
		description: 'Genera palabras desordenadas para ordenar.',
		link: '/activities/word-scramble-generator',
		icon: '/assets/undraw_specs_re_546x.svg',
		tier: 1,
	},
	{
		name: 'Generador de Sinónimos',
		description:
			'Crea listas de palabras y sus sinónimos contextualizados.',
		link: '/activities/synonyms-generator',
		icon: '/assets/undraw_file_searching_re_3evy.svg',
		tier: 1,
	},
	{
		name: 'Generador de Antónimos',
		description:
			'Crea listas de palabras y sus antónimos contextualizados.',
		link: '/activities/antonyms-generator',
		icon: '/assets/undraw_file_searching_re_3evy.svg',
		tier: 1,
	},
	{
		name: 'Crucigramas',
		description: 'Genera crucigramas para tus alumnos.',
		link: '/activities/crosswords-generator',
		icon: '/assets/undraw_file_searching_re_3evy.svg',
		tier: 1,
	},
	{
		name: 'Sopas de Letras',
		description: 'Genera sopas de letras por niveles y respuestas.',
		link: '/activities/wordsearch-generator',
		icon: '/assets/undraw_file_searching_re_3evy.svg',
		tier: 1,
	},
	{
		name: 'Suma',
		description: 'Genera Hojas de suma con hoja de respuestas.',
		link: '/activities/addition-generator',
		icon: '/assets/undraw_new_entries_re_cffr.svg',
		tier: 1,
	},
	{
		name: 'Resta',
		description: 'Genera Hojas de resta con hoja de respuestas.',
		link: '/activities/subtraction-generator',
		icon: '/assets/undraw_new_entries_re_cffr.svg',
		tier: 1,
	},
	{
		name: 'Multiplicación',
		description: 'Genera Hojas de multiplicación con sus respuestas.',
		link: '/activities/multiplication-generator',
		icon: '/assets/undraw_new_entries_re_cffr.svg',
		tier: 1,
	},
	{
		name: 'División',
		description: 'Crea ejercicios de división personalizados',
		link: '/activities/division-generator',
		icon: '/assets/undraw_new_entries_re_cffr.svg',
		tier: 1,
	},
	{
		name: 'Ejercicios Mixtos',
		description: 'Genera ejercicios mixtos de operaciones basicas.',
		link: '/activities/mixed-operations-generator',
		icon: '/assets/undraw_new_entries_re_cffr.svg',
		tier: 1,
	},
	{
		name: 'Ecuaciones',
		description: 'Ejercicios con ecuaciones',
		link: '/activities/equations-generator',
		icon: '/assets/undraw_new_entries_re_cffr.svg',
		tier: 1,
	},
	{
		name: 'Recta Numérica',
		description: 'Genera Hojas de ejercicios con la recta numérica.',
		link: '/activities/number-line-generator',
		icon: '/assets/undraw_new_entries_re_cffr.svg',
		tier: 1,
	},
	{
		name: 'Planos Cartesianos',
		description: 'Genera Hojas con plantillas de planos cartesianos.',
		link: '/activities/cartesian-coordinates-generator',
		icon: '/assets/undraw_new_entries_re_cffr.svg',
		tier: 1,
	},
	{
		name: 'Sudoku',
		description:
			'Genera Sudoku de diferentes niveles de dificultad y sus respuestas.',
		link: '/activities/sudoku-generator',
		icon: '/assets/undraw_game_day_ucx9.svg',
		tier: 1,
	},
	{
		name: 'Reflexiones Diarias',
		description: 'Crea reflexiones personalizadas para tus estudiantes',
		link: '/resources/reflection-generator',
		icon: '/assets/undraw_creative-thinking_ruwx.svg',
		tier: 1,
	},
	{
		name: 'Rompehielos',
		description: 'Crea actividades dinámicas para iniciar tus clases',
		link: '/resources/icebreaker-generator',
		icon: '/assets/undraw_team-up_qeem.svg',
		tier: 1,
	},
	{
		name: 'Trabalenguas',
		description: 'Crea trabalenguas divertidos para tus clases',
		link: '/activities/tongue-twister-generator',
		icon: '/assets/undraw_things-to-say_f5mi.svg',
		tier: 1,
	},
	{
		name: 'Problemas Matemáticos',
		description: 'Crea problemas contextualizados para tus clases',
		link: '/activities/math-problem-generator',
		icon: '/assets/undraw_mathematics_hc2c.svg',
		tier: 1,
	},
];
