import { AppEntry } from '../core';

export const assessmentTools: AppEntry[] = [
	{
		name: 'Generador de Exámenes',
		description: 'Genera exámenes instantaneamente.',
		link: '/assessments/test-generator',
		icon: '/assets/undraw_exams_d2tf.svg',
		tier: 2,
	},
	{
		name: 'Evaluación Diagnóstica',
		description: 'Genera Pruebas Diagnosticas Facilmente.',
		link: '/assessments/diagnostic-evaluation-generator',
		icon: '/assets/undraw_personal-goals_f9bb.svg',
		tier: 3,
	},
	// {
	// 	link: '/assessments/formation',
	// 	name: 'Evaluación Formativa',
	// 	icon: '/assets/learning.svg',
	// 	description: 'Herramientas interactivas para evaluar en tiempo real.',
	// 	tier: 4,
	// },
	{
		name: 'Generador de Listas de Cotejo',
		description: 'Genera listas de cotejo de forma rápida y fácil',
		link: '/assessments/checklist-generator',
		icon: '/assets/undraw_check-boxes_ewf2.svg',
		tier: 2,
	},
	{
		name: 'Registro Anecdótico',
		description: 'El registro anecdótico hecho fácil.',
		link: '/assessments/log-registry-generator',
		icon: '/assets/undraw_upload_image_re_svxx.svg',
		tier: 2,
	},
	{
		name: 'Generador de Guía de Observación',
		description: 'Elabora una guía de observación para tus actividades.',
		link: '/assessments/observation-sheet',
		icon: '/assets/checklist.svg',
		tier: 1,
	},
	{
		name: 'Generador de Rúbricas',
		description: 'Genera rúbricas para cualquier tema y nivel.',
		link: '/assessments/rubric-generator',
		icon: '/assets/checklist.svg',
		tier: 2,
	},
	{
		name: 'Generador de Rúbricas por Lote',
		description: 'Genera rúbricas por asignatura.',
		link: '/assessments/rubric-lot-generator',
		icon: '/assets/undraw_choose_5kz4.svg',
		tier: 2,
	},
	{
		name: 'Generador de Escala de Estimación',
		description: 'Escalas de estimación para evaluar.',
		link: '/assessments/estimation-scale',
		icon: '/assets/checklist.svg',
		tier: 1,
	},
	{
		name: 'Sistemas de Calificación',
		description: 'Informes detallados para cada necesidad.',
		link: '/assessments/grading-systems',
		icon: '/assets/undraw_portfolio_website_re_jsdd.svg',
		tier: 1,
	},
	// {
	// 	link: '/assessments/reviews',
	// 	name: 'Encuestas y Retroalimentación',
	// 	icon: '/assets/review.svg',
	// 	description: 'Recopilación de retroalimentación para mejorar la enseñanza.',
	// 	tier: 5,
	// },
];
