import { AppEntry } from '../core/interfaces'

export const resourcesTools: AppEntry[] = [
    {
        name: 'Ganchos para la clase',
        description: 'Crea ideas atractivas para iniciar tus lecciones',
        link: ['/resources', 'class-hook-generator'],
        categories: ['Actividades', 'Planificación'],
        icon: '/assets/undraw_sharing-knowledge_pu0e.svg',
        tier: 2,
    },
    {
        name: 'Generador de Cuentos',
        description: 'Crea cuentos originales adaptados a tus estudiantes',
        link: ['/resources', 'story-generator'],
        categories: ['Actividades'],
        icon: '/assets/undraw_book-writer_ri5u.svg',
        tier: 3,
    },
    {
        name: 'Generador de Poesía',
        description: 'Crea poemas originales para inspirar a tus estudiantes',
        link: ['/resources', 'poem-generator'],
        categories: ['Actividades'],
        icon: '/assets/undraw_writer_r7ca.svg',
        tier: 3,
    },
    {
        name: 'Generador de Fábulas',
        description: 'Crea fábulas con moralejas para tus clases',
        link: ['/resources', 'fable-generator'],
        categories: ['Actividades'],
        icon: '/assets/undraw_refreshing-beverage_w8al.svg',
        tier: 3,
    },
    {
        name: 'Generador de Chistes',
        description: 'Crea chistes apropiados para tus estudiantes',
        link: ['/resources', 'joke-generator'],
        categories: ['Actividades'],
        icon: '/assets/undraw_coffee_7r49.svg',
        tier: 3,
    },
    {
        name: 'Generador de Adivinanzas',
        description:
            'Crea adivinanzas ingeniosas para desafiar a tus estudiantes',
        link: ['/resources', 'riddle-generator'],
        categories: ['Actividades'],
        icon: '/assets/undraw_body-text_b6qq.svg',
        tier: 3,
    },
    {
        name: 'Generador de Curiosidades',
        description: 'Despierta el interés con datos sorprendentes',
        link: ['/resources', 'fun-fact-generator'],
        categories: ['Actividades'],
        icon: '/assets/undraw_startled_ez5h.svg',
        tier: 3,
    },
    {
        name: 'Generador de Refranes',
        description: 'Encuentra refranes y su significado para tus clases',
        link: ['/resources', 'proverb-generator'],
        categories: ['Actividades'],
        icon: '/assets/undraw_blooming_g9e9.svg',
        tier: 3,
    },
    {
        name: 'Generador de Canciones',
        description: 'Crea letras de canciones originales para tus actividades',
        link: ['/resources', 'song-generator'],
        categories: ['Actividades'],
        icon: '/assets/undraw_compose-music_9403.svg',
        tier: 3,
    },
    {
        name: 'Generador de Artículo Expositivo',
        description: 'Crea ejemplos de artículos expositivos para tus clases',
        link: ['/resources', 'expository-article-generator'],
        categories: ['Actividades'],
        icon: '/assets/undraw_sharing-articles_agyr.svg',
        tier: 3,
    },
    {
        name: 'Papel Cuadriculado',
        description: 'Genera Hojas cuadriculadas para geometría.',
        link: ['/resources', 'graph-paper'],
        categories: ['Hojas de Trabajo'],
        icon: '/assets/undraw_new_entries_re_cffr.svg',
        tier: 3,
    },
    {
        link: ['/resources', 'games'],
        categories: ['Juegos'],
        name: 'Juegos Educativos',
        icon: '/assets/games.svg',
        description:
            'Juegos educativos para hacer el aprendizaje más interactivo y divertido.',
        tier: 4,
    },
    {
        name: 'Seguimiento del Estudiante',
        description: 'Estadísticas del rendimiento estudiantil.',
        link: ['/resources', 'tracking'],
        categories: ['Evaluación'],
        icon: '/assets/grade.svg',
        tier: 4,
    },
];
