export const COMPETENCE = [
    {
        name: 'Comunicativa',
        grade: 'PRIMERO',
        subject: 'EDUCACION_ARTISTICA',
        level: 'PRIMARIA',
        entries: [],
        criteria: [],
    },
    {
        name: 'Comunicativa',
        grade: 'SEGUNDO',
        subject: 'EDUCACION_ARTISTICA',
        level: 'PRIMARIA',
        entries: [],
        criteria: [],
    },
    {
        name: 'Comunicativa',
        grade: 'TERCERO',
        subject: 'EDUCACION_ARTISTICA',
        level: 'PRIMARIA',
        entries: [],
        criteria: [],
    },
    {
        name: 'Comunicativa',
        grade: 'CUARTO',
        subject: 'EDUCACION_ARTISTICA',
        level: 'PRIMARIA',
        entries: [],
        criteria: [],
    },
    {
        name: 'Comunicativa',
        grade: 'QUINTO',
        subject: 'EDUCACION_ARTISTICA',
        level: 'PRIMARIA',
        entries: [],
        criteria: [],
    },
    {
        name: 'Comunicativa',
        grade: 'SEXTO',
        subject: 'EDUCACION_ARTISTICA',
        level: 'PRIMARIA',
        entries: [],
        criteria: [],
    },
    {
        name: 'Pensamiento Lógico, Creativo y Crítico; Resolución de Problemas; Tecnológica y Científica',
        grade: 'PRIMERO',
        subject: 'EDUCACION_ARTISTICA',
        level: 'PRIMARIA',
        entries: [],
        criteria: [],
    },
    {
        name: 'Pensamiento Lógico, Creativo y Crítico; Resolución de Problemas; Tecnológica y Científica',
        grade: 'SEGUNDO',
        subject: 'EDUCACION_ARTISTICA',
        level: 'PRIMARIA',
        entries: [],
        criteria: [],
    },
    {
        name: 'Pensamiento Lógico, Creativo y Crítico; Resolución de Problemas; Tecnológica y Científica',
        grade: 'TERCERO',
        subject: 'EDUCACION_ARTISTICA',
        level: 'PRIMARIA',
        entries: [],
        criteria: [],
    },
    {
        name: 'Pensamiento Lógico, Creativo y Crítico; Resolución de Problemas; Tecnológica y Científica',
        grade: 'CUARTO',
        subject: 'EDUCACION_ARTISTICA',
        level: 'PRIMARIA',
        entries: [],
        criteria: [],
    },
    {
        name: 'Pensamiento Lógico, Creativo y Crítico; Resolución de Problemas; Tecnológica y Científica',
        grade: 'QUINTO',
        subject: 'EDUCACION_ARTISTICA',
        level: 'PRIMARIA',
        entries: [],
        criteria: [],
    },
    {
        name: 'Pensamiento Lógico, Creativo y Crítico; Resolución de Problemas; Tecnológica y Científica',
        grade: 'SEXTO',
        subject: 'EDUCACION_ARTISTICA',
        level: 'PRIMARIA',
        entries: [],
        criteria: [],
    },
    {
        name: 'Ética y Ciudadana; Desarrollo Personal y Espiritual; Ambiental y de la Salud',
        grade: 'PRIMERO',
        subject: 'EDUCACION_ARTISTICA',
        level: 'PRIMARIA',
        entries: [],
        criteria: [],
    },
    {
        name: 'Ética y Ciudadana; Desarrollo Personal y Espiritual; Ambiental y de la Salud',
        grade: 'SEGUNDO',
        subject: 'EDUCACION_ARTISTICA',
        level: 'PRIMARIA',
        entries: [],
        criteria: [],
    },
    {
        name: 'Ética y Ciudadana; Desarrollo Personal y Espiritual; Ambiental y de la Salud',
        grade: 'TERCERO',
        subject: 'EDUCACION_ARTISTICA',
        level: 'PRIMARIA',
        entries: [],
        criteria: [],
    },
    {
        name: 'Ética y Ciudadana; Desarrollo Personal y Espiritual; Ambiental y de la Salud',
        grade: 'CUARTO',
        subject: 'EDUCACION_ARTISTICA',
        level: 'PRIMARIA',
        entries: [],
        criteria: [],
    },
    {
        name: 'Ética y Ciudadana; Desarrollo Personal y Espiritual; Ambiental y de la Salud',
        grade: 'QUINTO',
        subject: 'EDUCACION_ARTISTICA',
        level: 'PRIMARIA',
        entries: [],
        criteria: [],
    },
    {
        name: 'Ética y Ciudadana; Desarrollo Personal y Espiritual; Ambiental y de la Salud',
        grade: 'SEXTO',
        subject: 'EDUCACION_ARTISTICA',
        level: 'PRIMARIA',
        entries: [],
        criteria: [],
    },
]